version: "3.9"

services:
  nginx:
    container_name: quiz-l10-nginx
    build: ./docker/nginx
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php

  php:
    container_name: quiz-l10-php
    build: ./docker/php/
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    env_file:
      - ./.env
    depends_on:
      - mariadb

  mariadb:
    container_name: quiz-l10-mariadb
    build: ./docker/mysql
    volumes:
        - ./docker/mysql/data/mariadb:/var/lib/mysql
    ports:
        - 3306:3306
    env_file:
        - ./.env
  
  mailhog:
    container_name: quiz-l10-mailhog
    build: ./docker/mailhog 
    ports:
        - 8025:8025
        - 1025:1025